### ISSUE TITLE
error sir

### ISSUE THREAD

**Issue by maianhbao1** [Zlkcyber/functot#8]
Attempting daily check-in...
Error: Error: HTTP error! Status: 400
    at coday (F:\FUNCTOT\functot-main\main.js:20:37)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async loginAndCheckIn (F:\FUNCTOT\functot-main\main.js:52:33)
    at async main (F:\FUNCTOT\functot-main\main.js:76:40)
Check-in not available yet.

**Comment by Kartang12** [comment]
What proxy do u use?
